# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [2]:
import numpy as np
sqrmtr=[50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
rooms=[2, 2, 3, 2, 3, 3, 3, 4, 2, 4]
price=[400, 450, 550, 640, 430, 560, 700, 670, 900, 800]
houses= np.array([sqrmtr, rooms, price])

2. Transpose the array you have created, so that every line can represent features of one house.

In [6]:
new_houses=houses.T

3. Display the shape of the array and explain what it means.

In [7]:
print(new_houses)

[[ 50   2 400]
 [ 55   2 450]
 [ 60   3 550]
 [ 65   2 640]
 [ 70   3 430]
 [ 75   3 560]
 [ 80   3 700]
 [ 85   4 670]
 [ 90   2 900]
 [ 95   4 800]]


Every row of the array represents a house with several properties. These properties are displayed with columns as square meter, number of rooms and price respectively. 

4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [8]:
def array_zeros_ones(x,y):
    
    array_ones = np.ones((x,y))
    len_rows = len(array_ones)
    len_cols = len(array_ones[0])
    for i in range(len_rows):
        for j in range(len_cols):
            if i % 2 ==0 and j % 2 == 0:
                array_ones[i,j] = 0
    return array_ones

array_zeros_ones(10,10)

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])